---
# 1. TẠO "THẺ NHÂN VIÊN" (SERVICE ACCOUNT) ĐỂ APP CÓ QUYỀN VÀO S3
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orishop-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::808999395759:role/quyenlt-orishop-s3-role

---
# 2. TRIỂN KHAI ỨNG DỤNG LÊN CLUSTER (DEPLOYMENT)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orishop-app
spec:
  replicas: 2 # Chạy 2 Pod để đảm bảo không bao giờ sập web
  selector:
    matchLabels:
      app: orishop
  template:
    metadata:
      labels:
        app: orishop
    spec:
      serviceAccountName: orishop-sa # Giao thẻ nhân viên cho Pod
      containers:
      - name: orishop
        image: tobi1008/orishop:latest # Image sẽ được Jenkins đẩy lên
        ports:
        - containerPort: 8091
        env:
        # --- KẾT NỐI DATABASE (RDS MYSQL) ---
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://orishop-db.ch8mw2wuqs14.ap-southeast-1.rds.amazonaws.com:3306/orishop"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "OriShop12345!"
        
        # --- KẾT NỐI KHO ẢNH (AWS S3) ---
        - name: AWS_S3_BUCKET_NAME
          value: "com-quyenlt-media-op340i"
        - name: AWS_REGION
          value: "ap-southeast-1"
kubectl get pods -n default                                                 
---
# 3. MỞ CỬA CHO KHÁCH HÀNG TRUY CẬP (LOAD BALANCER SERVICE)
apiVersion: v1
kind: Service
metadata:
  name: orishop-service
spec:
  type: LoadBalancer # Báo AWS cấp cho 1 cái tên miền (URL) Public
  selector:
    app: orishop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8091