# 1. Khai báo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orishop-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: orishop
  template:
    metadata:
      labels:
        app: orishop
    spec:
      containers:
      - name: orishop-app
        image: tobi1008/orishop:latest
        ports:
        - containerPort: 8091 # <--- Đổi thành 8091 (Cổng app đang chạy)

---
# 2. Khai báo Service (Cửa ngõ mạng)
apiVersion: v1
kind: Service
metadata:
  name: orishop-service
spec:
  selector:
    app: orishop
  ports:
    - protocol: TCP
      port: 80          # Cổng mà các app khác trong cụm K8s gọi vào
      targetPort: 8091  # <--- Trỏ chính xác đích đến là 8091 của Container